apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |  
    - rolearn: arn:aws:iam::705799169873:role/eksctl-prod-nodegroup-linux-nodes-NodeInstanceRole-XKX6F0UNO853
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
